language: cpp

env:
  global:
    - OMP_NUM_THREADS=4
    - BOOST_BASENAME=boost_1_62_0
    - AMDAPPSDKROOT=${HOME}/AMDAPPSDK
    - secure: "A5GuWMfy2tamED4Xq/h1hXSAX18qemLuhaX3mLD77VMv6Hx2ZPAPXXDuRwg+Htoqccz3DQ3ezA5tf/D2PXffbOvkQeXMKkOBqHLy4aReZm9L+UajPETrQVW2bWBAuVJXMJbJEqdOv+QAEXf82Eml25zGp2r7L0J+FO5nrPtSeqE="

matrix:
  include:
  - os: osx
    osx_image: xcode9.1
    env: VEXCL_BACKEND=OpenCL

addons:
  apt:
    packages:
    - opencl-headers

cache:
    directories:
        - ${HOME}/${BOOST_BASENAME}/boost
        - ${HOME}/${BOOST_BASENAME}/stage/lib
        - ${AMDAPPSDKROOT}

before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ] ; then source .travis/install_amd_sdk.sh ; fi
    - if  [ "$TRAVIS_OS_NAME" = "linux" ] ; then source .travis/install_boost.sh ; fi
    - cmake --version

script:
    - mkdir -p build && cd build
    - cmake -DVEXCL_TEST_COVERAGE=ON -DVEXCL_BUILD_TESTS=ON -DVEXCL_BACKEND=${VEXCL_BACKEND} ..
    - make -j2
    - export CPATH=${CPATH}:${BOOST_ROOT}
    - if [ "$VEXCL_BACKEND" = "JIT" ] && [ "$CC" = "clang" ] ; then export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$(dirname $(which clang++))/../lib ; fi
    - ctest --output-on-failure
